# Generated by Django 5.2.6 on 2025-09-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=255, verbose_name='متن دکمه')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان اصلی')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='زیرعنوان')),
            ],
            options={
                'verbose_name': 'بخش هدر سایت',
                'verbose_name_plural': 'بخش\u200cهای هدر سایت',
            },
        ),
    ]
