# Generated by Django 5.2.6 on 2025-09-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پلن')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('per_month', models.BooleanField(default=True, verbose_name='پرداخت ماهانه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه')),
                ('features', models.TextField(blank=True, null=True, verbose_name='ویژگی\u200cها (هر خط یک ویژگی)')),
                ('is_popular', models.BooleanField(default=False, verbose_name='محبوب')),
                ('button_text', models.CharField(default='اکنون بخرید', max_length=100, verbose_name='متن دکمه')),
                ('button_link', models.URLField(default='#', verbose_name='لینک دکمه')),
            ],
            options={
                'verbose_name': 'پلن محصول',
                'verbose_name_plural': 'پلن\u200cهای محصولات',
            },
        ),
    ]
