# Generated by Django 5.2.6 on 2025-09-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_feature_alter_productplan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام شخص')),
                ('role', models.CharField(max_length=255, verbose_name='سمت/شرکت')),
                ('avatar', models.ImageField(upload_to='testimonials/', verbose_name='تصویر کاربر')),
                ('message', models.TextField(verbose_name='متن نظر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
            },
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
