# Generated by Django 5.2.6 on 2025-09-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان ویژگی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon', models.CharField(max_length=100, verbose_name='کلاس آیکون (Iconify)')),
                ('link', models.URLField(default='#', verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
            },
        ),
    ]
