# Generated by Django 5.2.6 on 2025-10-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.ImageField(upload_to='features/', verbose_name='آیکون (تصویر)'),
        ),
    ]
