# Generated by Django 5.2.6 on 2025-10-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پروژه')),
                ('category', models.CharField(max_length=100, verbose_name='دسته\u200cبندی')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='تصویر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک جزئیات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نمونه\u200cکار',
                'verbose_name_plural': 'نمونه\u200cکارها',
                'ordering': ['-created_at'],
            },
        ),
    ]
